#!/usr/bin/python

# -*- coding: utf-8 -*-

# ckstyle: Check document style with own style pattern
# written by tsugikazu shibata 2018(c)

patterns = [
    #  "style check pattern", "error message if we found the pattern"
    [u"[ａ-ｚＡ-Ｚ]", "全角アルファベットの利用は勧めません"],
    [u"[０-９]", "全角数字の利用は勧めません"],
    [u"[[ｳ-ﾎ](ﾟ|ﾞ)]", "半角カタカナの利用は勧めません"],
    [u"[ｦ-ﾝ]", "半角カタカナの利用は勧めません"],
    [u"[｡､]", "半角句読点の利用は勧めません"],
    [u"[．，]", "全角ピリオドとカンマの利用は勧めません"],
    [u"[（）？！i]", "全角の（）？！の利用は勧めません、半角にしましょう"],
    [u"[｢｣", "カギカッコ「」は全角をお勧めします"],
    [u"コミュニティー", "コミュニティ"],
    [u"セキュリティー", "セキュリティ"],
    [u"カテゴリー", "カテゴリ"],
    [u"コンピューター", "コンピュータ"],
    [u"リポジトリー", "リポジトリ"],
    [u"ディレクトリー", "ディレクトリ"],
    [u"ユーティリティー", "ユーティリティ"],
    [u"レジストリー", "レジストリ"],
    [u"プラットホーム", "プラットフォーム"],
    [u"アイデンティティー", "アイデンティティ"],
    [u"クリエーティブ", "クリエィティブ"],
    [u"リヌクス", "リナックス"],
    [u"インターフェース", "インターフェイス"],
    [u"コンパイラー", "コンパイラ"],
    [u"オープン ソース", "オープンソース"]
]


def listpatterns():
    # Not used now but maybe useful for futre style improvements
    global patterns
    num = len(patterns)
    print "num patters:", num
    for p in patterns:
        print p[0], " ", p[1]


def chkline(lineno, line):
    import re
    line = line.decode("utf-8")
    find = 0
    for p in patterns:
        result = re.findall(p[0], line)
        if result:
            find = find + 1
            print "{0:03d}:".format(lineno), line,
            print p[1]
    return find


import sys
if __name__ == "__main__":

    #listpatterns()
    args = sys.argv
    if len(args) <= 1:
        print "Please specify filename"
        sys.exit(-10)
    lineno = 1
    findnum = 0
    with open(sys.argv[1], 'r') as f:
        for line in f:
            fn = chkline(lineno, line)
            findnum = findnum + fn
            lineno = lineno + 1

    if findnum > 0:
        print findnum, "issue found"
    exit(findnum)
