#!/usr/bin/python3
# -*- coding: utf-8 -*-

# ckstyle: Check document style with own style pattern
# written by tsugikazu shibata 2018(c)

patterns = [
    #  "style check pattern", "error message if we found the pattern"
    [u"及び", u"接続詞 および はひらがなにしましょう"],
    [u"且つ", u"接続詞 かつ はひらがなにしましょう"],
    [u"而も", u"接続詞 しかも はひらがになしましょう"],
    [u"又は", u"接続詞 または はひらがなにしましょう"],
    [u"或いは", u"接続詞 あるいは はひらがなにしましょう"],
    [u"即ち", u"接続詞 すなわち はひらがなにしましょう"],

    [u"の通りです", u"参照などを示す とおり は漢字ではなくひらがなにしましょう"],
    [u"[0-9]とおり", u"種類などを示す 通りはひらがなではなく漢字にしましょう"],
    [u"して下さい", u"動作を要求する ください はひらがなにしましょう"],

    [u"[なのる]事[ぁ-ん]", u"用語でない場合には ひらがなの こと を使いましょう"],
    [u"[なのる]為[ぁ-ん]", u"用語でない場合には ひらがなの ため を使いましょう"],

    [u"(です；|ます；).", u"文の区切りはセミコロンでなく、句点「。」で区切りましょう"],
    [u"(です：|ます：).", u"文の区切りはコロンでなく、句点「。」で区切りましょう"],

    [u"[０-９]本", "日本語の数字を表す場合は半角数字を使いましょう"],
    [u"[０-９]部", "日本語の数字を表す場合は半角数字を使いましょう"],
    [u"[０-９]冊", "日本語の数字を表す場合は半角数字を使いましょう"],
    [u"[０-９]年", "日本語の数字を表す場合は半角数字を使いましょう"],
    [u"[０-９]段", "日本語の数字を表す場合は半角数字を使いましょう"],
    [u"[０−９][つ弾]", "日本語の数字を表す場合は半角数字を使いましょう"],

#    [u"[[ｳ-ﾎ](ﾟ|ﾞ)]", "半角カタカナの利用は勧めません"],
#    [u"[ｦ-ﾝ]", "半角カタカナの利用は勧めません"],
#    [u"[｡､]", "半角句読点の利用は勧めません"],
#    [u"[．，]", "全角ピリオドとカンマの利用は勧めません"],
#    [u"[（）？！]", u"全角の（）？！の利用は勧めません、半角にしましょう"],
#    [u"[｢｣]", "カギカッコ「」は全角をお勧めします"],
]


def listpatterns():
    # Not used now but maybe useful for futre style improvements
    global patterns
    num = len(patterns)
    print ("num patters:", num)
    for p in patterns:
        print (p[0], " ", p[1])


def chkline(lineno, line):
    import re
    find = 0
    if len(line) <= 1:
        return (find)
    for p in patterns:
        result = re.findall(p[0], line)
        if result:
            find = find + 1
            print ("{0:03d}:".format(lineno), line, end="")
            for s in result:
                #print ("**", s.encode("utf-8"), ":", p[1])
                print ("**", s, ":", p[1])
    return find


import sys
if __name__ == "__main__":

    args = sys.argv
    if len(args) <= 1:
        print ("Please specify filename")
        sys.exit(-10)
    lineno = 1
    findnum = 0
    with open(sys.argv[1], 'r', encoding='utf-8') as f:
        for line in f:
            fn = chkline(lineno, line)
            findnum = findnum + fn
            lineno = lineno + 1

    if findnum > 0:
        print (findnum, "issue found")
    exit(findnum)
